### ISSUE TITLE
Guide doesn't actually appear to ask ppl to read docs.cloud.gov

### ISSUE THREAD

**Issue by NoahKunin** [18F/product-guide#64]
Or link to it. As a result, we got a lot of ppl asking questions in Slack that are answered on docs.cloud.gov.

**Comment by annahsgraves** [comment]
@NoahKunin I'm sorry, but I don't understand what you're talking about. Is there a section your suggesting this be in? Can you point to the slack archive where this conversation is happening? I don't understand this issue. If there's a particular place you think this belongs, feel free to file a PR. Maintenance on this guide is minimal at this time due to bandwidth and staffing changes.
